#!/bin/sh
#!/bin/sh

# exit if no files changed
[[ `git diff-index --cached --name-only HEAD` ]] || exit 0

# run the unit tests
./node_modules/.bin/webpack --progress --colors --config webpack.cmd.config.js
#reject the commit in case of failures
if [[ $? != 0 ]]; then
    echo "Errores en el eslint"
    exit 1
fi;


#gulp test
/usr/local/bin/karma start karma.cmd.conf.js
# reject the commit in case of failures
if [[ $? != 0 ]]; then
    echo "Unit tests have failures. Commit rejected."
    exit 1
fi;
